### ISSUE TITLE
Exception thrown during mcpm command

### ISSUE THREAD

**Issue by XakepSDK** [jaredlll08/MCBot#34] opened 2019-07-30 10:42 UTC
Just execute `!mcpm func_77659_a 1.7.10`
It will throw this exception:
![grafik](https://user-images.githubusercontent.com/4938483/62123079-a85d7580-b2b6-11e9-8c87-e3dad71d6c7c.png)

This happens on my instance and on sponge server instance.

**Comment by tterrag1098** [comment] 2019-08-04 19:06
This is caused by the result overflowing the (arbitrary) length limits on embeds. I need to shorten the descriptions and perhaps lower the per-page amount of results.

**Comment by tterrag1098** [comment] 2019-08-05 06:16
Should be mostly resolved by 977725c06feb3d44bf61526a2ae4414664485ef1 with better error handling for that kind of exception added in 9281c8b9837dd3945889dae83197335f1790af21

**Closed as completed by tterrag1098** 2019-08-05 06:16 UTC
Labels: bug
